name: Build and Deploy to WP Engine

#============================== WORKFLOW CONFIG ============================

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    types:
      - closed
    branches:
      - develop
      - staging
      - main

# Workflow Environment Variables
env:
  # Development branch and environment variables
  DEVELOPMENT_BRANCH: develop
  WPENGINE_DEVELOPMENT_ENV: dev-env
  
  # Staging branch and environment variables
  STAGING_BRANCH: staging
  WPENGINE_STAGING_ENV: stg-env

  # Production branch and environment variables
  PRODUCTION_BRANCH: main
  WPENGINE_PRODUCTION_ENV: prod-env

  # The theme folder that requires assets to be built before deploying files
  WP_THEME_FOLDER: theme-folder

#============================ END WORKFLOW CONFIG ==========================

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == env.DEVELOPMENT_BRANCH || github.ref_name == env.STAGING_BRANCH || github.ref_name == env.PRODUCTION_BRANCH || (github.event.pull_request.merged && (github.base_ref == env.DEVELOPMENT_BRANCH || github.base_ref == env.STAGING_BRANCH || github.base_ref == env.PRODUCTION_BRANCH))
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "wp-content/themes/$WP_THEME_FOLDER"
      
      - name: Install JS Dependencies and Build Theme Assets
        run: |
          cd "wp-content/themes/$WP_THEME_FOLDER"
          npm i -ci
          npm run build
          rm -rf node_modules/
      
      - name: Deploy to WP Engine
        uses: padillaco/wpengine-deploy-action@main
        with:
          # Base directory for rsync
          base_directory: .

          # Destination directory for rsync in remote repository
          destination_directory: .

          # Comma-separated list of files and directories to exclude from sync
          exclude_list: .git, .github, .gitmodules, node_modules, .ddev

          # Source development branch and WP Engine environment name
          source_development_branch: ${{ env.DEVELOPMENT_BRANCH }}
          wpengine_development_env: ${{ env.WPENGINE_DEVELOPMENT_ENV }}

          # Source staging branch and WP Engine environment name
          source_staging_branch: ${{ env.STAGING_BRANCH }}
          wpengine_staging_env: ${{ env.WPENGINE_STAGING_ENV }}

          # Source production branch and WP Engine environment name
          source_production_branch: ${{ env.PRODUCTION_BRANCH }}
          wpengine_production_env: ${{ env.WPENGINE_PRODUCTION_ENV }}

          # SSH private key to use for remote repository authentication
          ssh_private_key: ${{ secrets.WPENGINE_SSH_PRIVATE_KEY }}
