name: 'Deploy to WP Engine'
description: 'Deploys local GitHub repo to WP Engine.'
author: 'padillaco'
branding:
  icon: 'cloud-lightning'
  color: 'yellow'
inputs:
  base_directory:
    description: 'Base directory for rsync'
    required: false
    default: '.'
  exclude_list:
    description: 'Comma-separated list of files and directories to exclude from sync'
    required: false
    default: '.git, .github, .gitmodules, node_modules'
  ssh_private_key:
    description: 'SSH private key to use for remote repository authentication'
    required: true
  source_development_branch:
    description: 'The development branch name in the source repository'
    required: false
  source_staging_branch:
    description: 'The staging branch name in the source repository'
    required: false
  source_production_branch:
    description: 'The production branch name in the source repository'
    required: true
  wpengine_development_env:
    description: 'The WP Engine development evironment name'
    required: false
  wpengine_staging_env:
    description: 'The WP Engine staging evironment name'
    required: false
  wpengine_production_env:
    description: 'The WP Engine production evironment name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Output Vars
      shell: bash
      id: output-vars
      run: |
        echo "GITHUB_CONTEXT $GITHUB_CONTEXT"
        echo "GITHUB_REF $GITHUB_REF"
        echo "GITHUB_REF_NAME $GITHUB_REF_NAME"
        echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF $GITHUB_BASE_REF"
        echo "inputs.wpengine_development_env ${{ inputs.wpengine_development_env }}"
        echo "INPUTS_SOURCE_DEVELOPMENT_BRANCH $INPUTS_SOURCE_DEVELOPMENT_BRANCH"
        echo "SOURCE_DEVELOPMENT_BRANCH $SOURCE_DEVELOPMENT_BRANCH"

        if [[ $GITHUB_REF_NAME == "${{ inputs.source_development_branch }}" ]]; then
          echo "yes 1"
        fi

        if [[ $GITHUB_REF_NAME == inputs.source_development_branch ]]; then
          echo "yes 2"
        fi

        echo "wpengine_deploy_env=inputs.source_development_branch" >> $GITHUB_OUTPUT
        echo "3 ${{ steps.output-vars.outputs.wpengine_deploy_env }}"
        
        echo "wpengine_deploy_env=${{ inputs.source_development_branch }}" >> $GITHUB_OUTPUT
        echo "4 ${{ steps.output-vars.outputs.wpengine_deploy_env }}"
    - name: INPUTS_CONTEXT
      shell: bash
      id: INPUTS_CONTEXT_OUTPUT
      run: echo "$INPUTS_CONTEXT"
    - name: Set Output Variables - WP Engine Environment
      shell: bash
      id: wpengine-deploy-env
      run: |
        if [[ inputs.source_development_branch != "" && $GITHUB_REF_NAME == inputs.source_development_branch ]]; then
          echo "wpengine_deploy_env=inputs.source_development_branch" >> $GITHUB_OUTPUT
        elif [[ $INPUT_SOURCE_STAGING_BRANCH != "" && $GITHUB_BASE_REF == $INPUT_SOURCE_STAGING_BRANCH ]]; then
          echo "wpengine_deploy_env=$INPUT_WPENGINE_STAGING_ENV" >> $GITHUB_OUTPUT
        elif [[ $INPUT_SOURCE_PRODUCTION_BRANCH != "" && $GITHUB_BASE_REF == $INPUT_SOURCE_PRODUCTION_BRANCH ]]; then
          echo "wpengine_deploy_env=$INPUT_WPENGINE_PRODUCTION_ENV" >> $GITHUB_OUTPUT
        else
          echo "No WP Engine environment was set for deployment."
          exit 1
        fi
    - name: Install rsync
      run: sudo apt-get install -y rsync
      shell: bash
